### PR TITLE
LRQA-61043 | Master

### PR DESCRIPTION
**Pull request by lucasneves91**

### CODE REVIEW

**Comment by lucasneves91** [comment]
ci:test:sf

**Comment by lucasneves91** [comment]
ci:test:sf

**Comment by lucasneves91** [comment]
ci:help

**Comment by lucasneves91** [comment]
ci:test:forms

**Comment by lucasneves91** [comment]
ci:test:relevant

**Comment by lucasneves91** [comment]
ci:test:acceptance

**Comment by palomaanunes** [comment]
@lucasneves91 about the unique failure, the Workflow QA already identified as a test fix and submitted a PR to put it in quarentine: https://github.com/brianchandotcom/liferay-portal/pull/92996/files. So, this failure is not related to your PR.

**Comment by palomaanunes** [comment]
@lucasneves91 about the common failure, the QAs already identified that it's a common problem: https://issues.liferay.com/browse/LRQA-61150 and it is not related to your PR.

Thus, move forward with your PR 👍

**Comment by lucasneves91** [comment]
ci:forward

**Pull request closed without merging**
