### PR TITLE
Poshi-116 Sub-Task Ocular implementation to Poshi

### PR DESCRIPTION
**Pull request by lucasneves91**
[POSHI-110](https://issues.liferay.com/browse/POSHI-110) - As a Tester writer, I should be able to use Ocular to compare images;

- Sending LiferaySelenium changes in poshi-core first.

[POSHI-116](https://issues.liferay.com/browse/POSHI-116) - Implementation of Ocular setup into Poshi context for image validation;

- Created methods that will need for Ocular Tool for this initial implementation.

### CODE REVIEW

**Comment by lucasneves91** [comment]
ci:test:sf

**Comment by lucasneves91** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
@lucasneves91, not sure if you saw my comment on [POSHI-110](https://issues.liferay.com/browse/POSHI-110), you'll need to send me purely the `LiferaySelenium` changes, apart from anything else (don't include BaseWebDriverImpl changes or anything from `poshi-runner`). We have to make `poshi-core` module changes first. 

Secondly, the methods you added in LiferaySelenium don't match what you implemented in BaseWebDriverImpl. 

What you added in LiferaySelenium: 
```
	public String getOcularResultImageDirName() throws Exception;
	public String getOcularSnapImageDirName() throws Exception;
	public void ocularConfig() throws Exception;
	public void ocularImageValidation(String locator) throws Exception;
```

What you implemented in BaseWebDriverImpl: 
```
	public String getOcularResultImageDirName()
	public String getOcularSnapImageDirName()
	public void ocularConfig()
	public boolean ocularImageValidation(String locator)
```

Whether you use `throws Exception` must be consistent (either have it, or don't have it). Additionally, is  `ocularImageValidation` supposed to be a `void` or `boolean` type? Types, names, arguments & their types, and exception throwing must all match between interfaces and their implementations. 

Additionally, could you explain how `ocularConfig` and `ocularImageValidation` would be used? I'm leaning on not including `ocularConfig` into LiferaySelenium, but we'll call it implicitly in ocular methods and also leaning towards renaming `ocularImageValidation`.

**Comment by lucasneves91** [comment]
@kenjiheigel
	Only ocularConfig and ocularImageValidation should throws Exceptions.
	Method ocularImageValidation is a boolean type.

	ocularConfig has to be used like standard configuration for ocular methods, setting the base location of baseline images (Snapshot) and setting the base location for result after comparision.
	and ocularImageValidation is a common method to compare the baseline image with a specific element.

	But you want to do something like merging these two methods in one?

```
	public String getOcularResultImageDirName();
	public String getOcularSnapImageDirName();
	public void ocularConfig() throws Exception;
	public boolean ocularImageValidation(String locator) throws Exception;
```

**Pull request closed without merging**
